name: automaton_simulator
description: "An interactive learning platform featuring simulators for finite automata, pushdown automata (PDA), and Turing machines. Designed for students and enthusiasts to explore, design, and test computational models with real-time visual simulations."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  arrow_path: ^3.1.0
  vector_math: ^2.1.4
  tutorial_coach_mark: ^1.2.11
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
